before:
  hooks:
    - make build

builds:
  - id: kb-summarizer
    main: ./cmd/kb-summarizer
    binary: kb-summarizer
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
