version: 2

before:
  hooks:
    - make build

builds:
  - id: kb-summarizer
    main: ./cmd/kb-summarizer
    binary: kb-summarizer
    env:
      - CGO_ENABLED=0

release:
  prerelease: auto

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"