name: Release

on:
  push:
    tags:
      - 'v*'

jobs:

  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write 
      # write is needed for:
      # - needed for creating releases
      # - OIDC for cosign's use in ecm-distro-tools/publish-image.
      # - Read vault secrets in rancher-eio/read-vault-secrets.
      id-token: write
    
    strategy:
      # For sequential execution, to leverage both docker buildx
      # caching and to avoid each job having to push the same layers
      # to the target registry.
      max-parallel: 1
      matrix:
        include:
          # Three images are created:
          # - Multi-arch manifest for both amd64 and arm64
          - tag-suffix: ""
            platforms: linux/amd64,linux/arm64
          # - arm64 manifest
          - tag-suffix: "-arm64"
            platforms: linux/arm64
          # - amd64 manifest
          - tag-suffix: "-amd64"
            platforms: linux/amd64

    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      - name: Create release
        if: matrix.tag-suffix == ''
        run: |
          gh release create ${{ github.ref_name }} --verify-tag --title "${{ github.ref_name }}" --generate-notes
        env:
          GH_TOKEN: ${{ github.token }}